[package]
name = "rustyneedle"
version = "0.1.0"
edition = "2021"

[lib]
name = "needle"
path = "src/lib.rs"

[[bin]]
name = "rustyneedle"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
ctor = "0.1.26"
nix = "0.26.2"
